# apiVersion: v1
# kind: Namespace
# metadata:
#   name: app2-wordpress
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  # namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql
            - name: WORDPRESS_DB_USER
              value: wpuser
            - name: WORDPRESS_DB_PASSWORD
              value: wppassword
            - name: WORDPRESS_DB_NAME
              value: wpdb
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  # namespace: default
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30082
